version: '3'

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn do_it_django_prj.wsgi:application --bind 0.0.0.0:8000
    volumes:
    - ./:/usr/src/app
    ports:
    - 8000:8000
    env_file:
    - ./envs/.env.dev
    depends_on:
      - db
# postgres sql
  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envs/.env.db
volumes:
  postgres_data: